### PR TITLE
Make important updates tothe README

### PR DESCRIPTION
**Pull request by lawrencehook**

### CODE REVIEW

**Comment by lawrencehook** [comment]
Hoping to add open source contributor to my Twitter bio, @atallahhezbor can you review?

**Comment by lawrencehook** [comment]
:P

**Comment by atallahhezbor** [comment]
Wow these are excellent and impactful changes. 

Unfortunately there is a typo in your PR title 
> Make important updates tothe README

so there is no way I can accept this

**Comment by lawrencehook** [comment]
I appreciate the effort and time you took to review my PR.

I know that in order to maintain a high standard of quality small errors cannot be tolerated, so I understand your decision to reject this pull request. In the future, I will only submit changes that pass my own sharpest scrutiny.

It is not easy to own a public code repo so thank you for providing the opportunity for potential collaborators to contribute to this project.

**Comment by lawrencehook** [comment]
@atallahhezbor 

I really want that Twitter bio, though. Can you grant a one-time exception?

**Comment by atallahhezbor** [comment]
@emumoo Your perseverance has inspired me. And upon second glance, I am enamored by the avant garde PR title. Of course I will merge this

**Comment by lawrencehook** [comment]
🙏

**Pull request merged**
